// Seed data for 12 Banarasi Silk Sarees
export const SEED_PRODUCTS = [
  {
    slug: 'royal-crimson-banarasi',
    title: 'Royal Crimson Banarasi',
    description: 'A regal deep-crimson pure silk Banarasi saree hand-woven in the ancient looms of Varanasi. Rich zari motifs of mango and lotus dance across the drape, finished with an intricate gold pallu. A timeless heirloom for weddings and grand occasions.',
    shortDescription: 'Deep crimson pure silk with intricate gold zari mango motifs.',
    category: 'Bridal Collection',
    price: 42500,
    salePrice: 34999,
    stock: 8,
    fabric: 'Pure Katan Silk',
    colour: 'Crimson',
    occasion: 'Wedding',
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1618901185975-d59f7091bcfe?w=1200&q=85',
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=1200&q=85',
    ],
  },
  {
    slug: 'antique-gold-heritage',
    title: 'Antique Gold Heritage',
    description: 'Woven with pure zari on an ivory base, this saree evokes centuries of Banarasi tradition. The delicate jangla pattern covers the entire body with an antique gold sheen that shimmers under candlelight.',
    shortDescription: 'Ivory silk with all-over antique gold zari jangla work.',
    category: 'Wedding Collection',
    price: 38000,
    salePrice: 31500,
    stock: 5,
    fabric: 'Pure Katan Silk',
    colour: 'Ivory',
    occasion: 'Wedding',
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1610030468706-9a6dbad49b0a?w=1200&q=85',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=85',
    ],
  },
  {
    slug: 'midnight-purple-jamdani',
    title: 'Midnight Purple Jamdani',
    description: 'A luxurious deep purple Banarasi Jamdani woven with fine silver-gold zari. Bold floral butis and a striking contrast border make this piece a statement of poise and grandeur.',
    shortDescription: 'Deep purple Jamdani with silver-gold floral butis.',
    category: 'Festive Collection',
    price: 28500,
    salePrice: 22999,
    stock: 12,
    fabric: 'Katan Silk Jamdani',
    colour: 'Purple',
    occasion: 'Festive',
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=85',
      'https://images.unsplash.com/photo-1641699862936-be9f49b1c38d?w=1200&q=85',
    ],
  },
  {
    slug: 'peacock-teal-tanchoi',
    title: 'Peacock Teal Tanchoi',
    description: 'The Tanchoi weave gives this teal-blue saree an unmistakable silken lustre. Peacock motifs in soft gold shimmer along the pallu — a modern classic for the discerning collector.',
    shortDescription: 'Peacock teal Tanchoi silk with soft gold peacock motifs.',
    category: 'Festive Collection',
    price: 24500,
    salePrice: 19999,
    stock: 15,
    fabric: 'Tanchoi Silk',
    colour: 'Teal',
    occasion: 'Festive',
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1610189335693-9e909b33aa32?w=1200&q=85',
      'https://images.unsplash.com/photo-1610030469668-8e9f641aaf27?w=1200&q=85',
    ],
  },
  {
    slug: 'blush-pink-kadhwa',
    title: 'Blush Pink Kadhwa',
    description: 'The kadhwa technique lends this delicate blush pink saree a raised, almost embroidered feel. Rose gold zari flowers bloom across a soft silk canvas, perfect for daytime celebrations.',
    shortDescription: 'Blush pink Kadhwa silk with rose-gold floral zari.',
    category: 'Traditional Collection',
    price: 21500,
    salePrice: 17999,
    stock: 20,
    fabric: 'Kadhwa Silk',
    colour: 'Pink',
    occasion: 'Reception',
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1610189338175-0782dfdb0c04?w=1200&q=85',
      'https://images.unsplash.com/photo-1727430228383-aa1fb59db8bf?w=1200&q=85',
    ],
  },
  {
    slug: 'onyx-black-zari',
    title: 'Onyx Black Zari',
    description: 'A show-stopping onyx black Banarasi with cascading silver-gold zari vines. The contrast is bold, cinematic and utterly unforgettable — designed for the woman who commands the room.',
    shortDescription: 'Onyx black silk with cascading silver-gold zari vines.',
    category: 'Bridal Collection',
    price: 35500,
    salePrice: 28999,
    stock: 6,
    fabric: 'Pure Katan Silk',
    colour: 'Black',
    occasion: 'Wedding',
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1610030469668-8e9f641aaf27?w=1200&q=85',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=85',
    ],
  },
  {
    slug: 'coral-sunrise-butti',
    title: 'Coral Sunrise Butti',
    description: 'Warm coral silk scattered with tiny gold butis — this saree captures the glow of a Varanasi sunrise. Light, elegant and endlessly wearable for festive gatherings.',
    shortDescription: 'Warm coral silk with tiny gold butis all over.',
    category: 'Festive Collection',
    price: 18500,
    salePrice: 14999,
    stock: 18,
    fabric: 'Katan Silk',
    colour: 'Coral',
    occasion: 'Festive',
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1727430228383-aa1fb59db8bf?w=1200&q=85',
      'https://images.unsplash.com/photo-1610189338175-0782dfdb0c04?w=1200&q=85',
    ],
  },
  {
    slug: 'emerald-forest-meenakari',
    title: 'Emerald Forest Meenakari',
    description: 'A rich emerald green saree with the rare Meenakari weave — coloured zari threads creating floral motifs like enamel work. Truly an heirloom in the making.',
    shortDescription: 'Emerald green Meenakari silk with coloured zari florals.',
    category: 'Wedding Collection',
    price: 32500,
    salePrice: 26999,
    stock: 7,
    fabric: 'Meenakari Silk',
    colour: 'Green',
    occasion: 'Wedding',
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1610189335693-9e909b33aa32?w=1200&q=85',
      'https://images.unsplash.com/photo-1641699862936-be9f49b1c38d?w=1200&q=85',
    ],
  },
  {
    slug: 'ruby-red-brocade',
    title: 'Ruby Red Brocade',
    description: 'A luxurious ruby red brocade saree with a densely woven gold pallu. The weight and drape speak of pure Katan silk in its most refined form.',
    shortDescription: 'Ruby red brocade silk with densely woven gold pallu.',
    category: 'Bridal Collection',
    price: 45500,
    salePrice: 37999,
    stock: 4,
    fabric: 'Pure Katan Silk',
    colour: 'Red',
    occasion: 'Wedding',
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1618901185975-d59f7091bcfe?w=1200&q=85',
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=1200&q=85',
    ],
  },
  {
    slug: 'champagne-mist-organza',
    title: 'Champagne Mist Organza',
    description: 'Feather-light Banarasi organza in champagne, sprinkled with tiny gold sequins and zari butis. Modern, airy and endlessly photogenic.',
    shortDescription: 'Champagne organza silk with gold zari butis and sequins.',
    category: 'New Arrivals',
    price: 16500,
    salePrice: 12999,
    stock: 22,
    fabric: 'Banarasi Organza',
    colour: 'Champagne',
    occasion: 'Reception',
    featured: false,
    images: [
      'https://images.pexels.com/photos/34155081/pexels-photo-34155081.jpeg?w=1200',
      'https://images.unsplash.com/photo-1610189338175-0782dfdb0c04?w=1200&q=85',
    ],
  },
  {
    slug: 'magenta-glow-tissue',
    title: 'Magenta Glow Tissue',
    description: 'Vibrant magenta tissue silk with a gold-woven base that catches every light. A modern take on tradition, ideal for cocktail receptions and sangeet nights.',
    shortDescription: 'Vibrant magenta tissue silk with gold-woven base.',
    category: 'Best Sellers',
    price: 22500,
    salePrice: 18499,
    stock: 11,
    fabric: 'Tissue Silk',
    colour: 'Magenta',
    occasion: 'Reception',
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1641699862936-be9f49b1c38d?w=1200&q=85',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=85',
    ],
  },
  {
    slug: 'ivory-pearl-classic',
    title: 'Ivory Pearl Classic',
    description: 'A timeless ivory Banarasi with pearl-white zari motifs. Understated, elegant and endlessly versatile — a true modern classic.',
    shortDescription: 'Ivory silk with pearl-white zari motifs — a modern classic.',
    category: 'Traditional Collection',
    price: 26500,
    salePrice: 21999,
    stock: 9,
    fabric: 'Pure Katan Silk',
    colour: 'Ivory',
    occasion: 'Wedding',
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1610030468706-9a6dbad49b0a?w=1200&q=85',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200&q=85',
    ],
  },
];
